proj03: main.0
	g++ -std=c+11 main

main.o:


employee.o: Employee.h Employee.cpp PrintVisitor.h
	g++ -std=c++11 -Wall -c Employee.cpp

group.o: Group.h Group.cpp PrintVisitor.h
	g++ -std=c++11 -Wall -c Group.cpp

pvisitor.o: PrintVisitor.h PrintVisitor.cpp Group.h 
	g++ -std=c++11 -Wall -c PrintVisitor.cpp

svisitor.o:  
	

cvisitor.o:

